### ISSUE TITLE
Weight-based joint training/inference across EEG channels

### ISSUE THREAD

**Issue by ambroiseodt** [ivadomed/MEEG-Brainstorm#11]
Currently, we resample the channels (eg n=64 channels) into a Cartesian space (eg: 128x128 matrix) to use the dependency between channels (spatial proximity of electrodes might be useful to detect spikes) but it makes a lot of data and increases training time

We would like to find another way to recover this dependency without using the 2D representation.
We thought about putting weight on channels to have a joint training/inference but don’t know how to and  which algorithm to use after.

An idea could be to associate neighbored channels by weight so that training is joint.
Distribution of weights could depend on times and depending on the spike zone, different channels would be gathered and features of their signals learned.

This is still an unfinished idea, any feedback or other approaches are welcome.
See below (colored circle represent weights) 
![Sans titre](https://user-images.githubusercontent.com/64415312/150438613-0b2aee93-8ebb-47be-8d77-8f8cfae5987f.png)

**Comment by jcohenadad** [comment]
Somewhat related to #7

**Comment by mpompolas** [comment]
I am not sure how this reduces complexity.
If I understand it correctly, you will have to do a combinatorial joint training : 
![image](https://user-images.githubusercontent.com/23224563/150582085-bc9c6c0a-54e3-461f-bbd4-1e5595928ad1.png)
where n is the total number of channels and k the hyperparameter of the number of channels for joint training.
I would need some explanation of what joint training means in practical terms: k channels as an input and you end up with multiple models for each combination? How are the models combined in the end?

Moreover, the spatial weight is equally distributed along a circle of a given channel, so the relative position information (left or right for example) between channels is lost - it could be ok if only 2 channels are combined, but for 3 and more this is definitely problematic.

I think this is still too premature to be evaluated. Perhaps you can elaborate more.

**Comment by ambroiseodt** [comment]
i was not necessarily thinking about an equally distributed weight on a circle it was a representation of them
But you are right: if joints are needed for each couples of channels, no decrease in data size is done 

I have to think about the idea and look for possibilities to order 2D points without loosing the space information to elaborate more on this issue 

Even without weight, I have to find a way to learn only using the channels coordinates
