### ISSUE TITLE
Update the README for external contributors to chip in

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/MEEG-Brainstorm#8]
It is currently difficult to get a grasp of the project (what is being done, who is doing what, etc.)

This info should be in the README.

**Comment by mpompolas** [comment]
done on https://github.com/ivadomed/MEEG-Brainstorm/commit/a08104e1c003211d4d5940c5fb3edc8882be604c

**Comment by jcohenadad** [comment]
thank you @mpompolas ! minor fixups here: https://github.com/ivadomed/MEEG-Brainstorm/commit/236d059410feb5eb5079003bef25e15a1418709b

i think we can now close this issue
